language: node_js
cache:
  directories:
  - $HOME/build/unfoldingWord-dev/node-gogs-client/node_modules
sudo: false
node_js:
- '5.1'
before_script:
- npm install
- npm install gulp -g
script: gulp
before_install:
- openssl aes-256-cbc -K $encrypted_e6ce7e8a422a_key -iv $encrypted_e6ce7e8a422a_iv -in config.json.enc -out tests/config.json -d